server:
  servlet:
    context-path: /minesweeper
  port: ${PORT}

spring:
  application:
    name: minesweeper

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER_URL}/${DB_NAME}?retryWrites=true&w=majority

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false